export const CONNECT_WALLET = 'CONNECT_WALLET'
export const PROFILE_REQUEST = 'PROFILE_REQUEST'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_FAIL = 'PROFILE_FAIL'

export const TEST_PROFILE_REQ = 'TEST_PROFILE_REQ'
export const TEST_PROFILE_SUCCESS = 'TEST_PROFILE_SUCCESS'
export const TEST_PROFILE_FAIL = 'TEST_PROFILE_FAIL'
