export const STAKE_CAPL_REQUEST = 'STAKE_CAPL_REQUEST'
export const STAKE_CAPL_SUCCESS = 'STAKE_CAPL_SUCCESS'
export const STAKE_CAPL_FAIL = 'STAKE_CAPL_FAIL'

export const STAKE_CRET_REQUEST = 'STAKE_CRET_REQUEST'
export const STAKE_CRET_SUCCESS = 'STAKE_CRET_SUCCESS'
export const STAKE_CRET_FAIL = 'STAKE_CRET_FAIL'

export const UN_STAKE_CAPL_REQUEST = 'UN_STAKE_CAPL_REQUEST'
export const UN_STAKE_CAPL_SUCCESS = 'UN_STAKE_CAPL_SUCCESS'
export const UN_STAKE_CAPL_FAIL = 'UN_STAKE_CAPL_FAIL'

export const UN_STAKE_CRET_REQUEST = 'UN_STAKE_CRET_REQUEST'
export const UN_STAKE_CRET_SUCCESS = 'UN_STAKE_CRET_SUCCESS'
export const UN_STAKE_CRET_FAIL = 'UN_STAKE_CRET_FAIL'

export const UN_STAKE_TIMER_REQUEST = 'UN_STAKE_TIMER_REQUEST'
export const UN_STAKE_TIMER_SUCCESS = 'UN_STAKE_TIMER_SUCCESS'
export const UN_STAKE_TIMER_FAIL = 'UN_STAKE_TIMER_FAIL'
export const UN_STAKE_TIMER_STATUS = 'UN_STAKE_TIMER_STATUS'


export const CLAIM_WITHDRAW_REQUEST = 'CLAIM_WITHDRAW_REQUEST'
export const CLAIM_WITHDRAW_SUCCESS = 'CLAIM_WITHDRAW_SUCCESS'
export const CLAIM_WITHDRAW_FAIL = 'CLAIM_WITHDRAW_FAIL'

export const CLEAR_HISTORY = 'CLEAR_HISTORY'
