export const VAULT_DEPOSIT_REQUEST = 'VAULT_DEPOSIT_REQUEST'
export const VAULT_DEPOSIT_SUCCESS = 'VAULT_DEPOSIT_SUCCESS'
export const VAULT_DEPOSIT_FAIL = 'VAULT_DEPOSIT_FAIL'

export const VAULT_WITHDRAW_REQUEST = 'VAULT_WITHDRAW_REQUEST'
export const VAULT_WITHDRAW_SUCCESS = 'VAULT_WITHDRAW_SUCCESS'
export const VAULT_WITHDRAW_FAIL = 'VAULT_WITHDRAW_FAIL'

export const VAULT_TRANSFORM_REQUEST = 'VAULT_TRANSFORM_REQUEST'
export const VAULT_TRANSFORM_SUCCESS = 'VAULT_TRANSFORM_SUCCESS'
export const VAULT_TRANSFORM_FAIL = 'VAULT_TRANSFORM_FAIL'

export const VAULT_CONVERT_REQUEST = 'VAULT_CONVERT_REQUEST'
export const VAULT_CONVERT_SUCCESS = 'VAULT_CONVERT_SUCCESS'
export const VAULT_CONVERT_FAIL = 'VAULT_CONVERT_FAIL'

export const GET_CONVERTED_USDC_CCPT_VALUES_SUCCESS =
  'GET_CONVERTED_USDC_CCPT_VALUES_SUCCESS'

export const GET_DEPOSITED_BALANCE_SUCCESS = 'GET_DEPOSITED_BALANCE_SUCCESS'


export const CLEAR_VALUES = 'CLEAR_VALUES'
