export const LIQUIDITY_DEPOSIT_REQUEST = 'LIQUIDITY_DEPOSIT_REQUEST'
export const LIQUIDITY_DEPOSIT_SUCCESS = 'LIQUIDITY_DEPOSIT_SUCCESS'
export const LIQUIDITY_DEPOSIT_FAIL = 'LIQUIDITY_DEPOSIT_FAIL'

export const LIQUIDITY_WITHDRAW_REQUEST = 'LIQUIDITY_WITHDRAW_REQUEST'
export const LIQUIDITY_WITHDRAW_SUCCESS = 'LIQUIDITY_WITHDRAW_SUCCESS'
export const LIQUIDITY_WITHDRAW_FAIL = 'LIQUIDITY_WITHDRAW_FAIL'

export const CLEAR_TRANSACTION_HISTORY = 'CLEAR_TRANSACTION_HISTORY'
