export const LIQUIDITY_DEPOSIT_REQUEST = 'LIQUIDITY_DEPOSIT_REQUEST'
export const LIQUIDITY_DEPOSIT_SUCCESS = 'LIQUIDITY_DEPOSIT_SUCCESS'
export const LIQUIDITY_DEPOSIT_FAIL = 'LIQUIDITY_DEPOSIT_FAIL'

export const LIQUIDITY_WITHDRAW_REQUEST = 'LIQUIDITY_WITHDRAW_REQUEST'
export const LIQUIDITY_WITHDRAW_SUCCESS = 'LIQUIDITY_WITHDRAW_SUCCESS'
export const LIQUIDITY_WITHDRAW_FAIL = 'LIQUIDITY_WITHDRAW_FAIL'

export const CLAIM_WITHDRAW_REQUEST = 'CLAIM_WITHDRAW_REQUEST'
export const CLAIM_WITHDRAW_SUCCESS = 'CLAIM_WITHDRAW_SUCCESS'
export const CLAIM_WITHDRAW_FAIL = 'CLAIM_WITHDRAW_FAIL'

export const CLEAR_TRANSACTION_HISTORY = 'CLEAR_TRANSACTION_HISTORY'

export const COOL_DOWN_PERIOD_REQUEST = 'COOL_DOWN_PERIOD_REQUEST'
export const COOL_DOWN_PERIOD_SUCCESS = 'COOL_DOWN_PERIOD_SUCCESS'
export const COOL_DOWN_PERIOD_FAIL = 'COOL_DOWN_PERIOD_FAIL'
export const COOL_DOWN_PERIOD_STATUS = 'COOL_DOWN_PERIOD_STATUS'
