export const TREASURY_WALLET_REQUEST = 'TREASURY_WALLET_REQUEST'
export const TREASURY_WALLET_SUCCESS = 'TREASURY_WALLET_SUCCESS'
export const TREASURY_WALLET_FAIL = 'TREASURY_WALLET_FAIL'
export const TREASURY_INFO_REQUEST = 'TREASURY_INFO_REQUEST'
export const TREASURY_INFO_SUCCESS = 'TREASURY_INFO_SUCCESS'

export const TREASURY_AMOUNT_REQUEST = 'TREASURY_AMOUNT_REQUEST'
export const TREASURY_AMOUNT_SUCCESS = 'TREASURY_AMOUNT_SUCCESS'
export const CLEAR_HISTORY = 'CLEAR_HISTORY'


