export const SWAPPING_REQUEST = 'SWAPPING_REQUEST'
export const SWAPPING_SUCCESS = 'SWAPPING_SUCCESS'
export const SWAPPING_FAIL = 'SWAPPING_FAIL'

export const GET_CONVERTED_USDC_VALUES_SUCCESS =
  'GET_CONVERTED_USDC_VALUES_SUCCESS'
export const GET_CONVERTED_CCPT_VALUES_SUCCESS =
  'GET_CONVERTED_CCPT_VALUES_SUCCESS'
export const GET_SWAP_TOKENS_BALANCE = 'GET_SWAP_TOKENS_BALANCE'

export const REMOVE_HASH = 'REMOVE_HASH'

export const PROFILE_REQ = 'PROFILE_REQ'
export const PROFILE_SUCC = 'PROFILE_SUCC'
export const PROFILE_FAIL = 'PROFILE_FAIL'

export const GET_CAPL_PRICE = 'GET_CAPL_PRICE'

